-- Reconciliation placeholder for migration 20260225201000
-- This migration was already applied on remote production DB history.
-- Intentionally no-op to align local migration directory with remote versions.
